### ISSUE TITLE
support for stream lib adapters

### ISSUE THREAD

**Issue by sirbarrence** [cyclejs/collection#20]
It would be nice if we could easily use Collection with other stream libs besides xstream, perhaps by supplying our stream adapter of choice to `Collection()` - as suggested by @Hypnosphi on gitter. Currently there seems to be a hard requirement for xstream sources only, so things break if our app's components use RxJS.

**Comment by Hypnosphi** [comment]
@Widdershin what do you think about it? Should we depend on https://github.com/whitecolor/cycle-convert or write conversions ourselves?

One thing that's worth keeping in mind is that usually if you use some stream library, you use it throughout your whole app. So if, for instance, rx5 is used, than `add$` will be rx5 observable, `Component` function takes rx5 sinks and returns rx5 sources, and all the selector functions return rx5 observables. `Collection` function itself should return an rx5 observable of collection, as do `Collection.merge` and `Collection.pluck`.

Maybe, instead of exporting `Collection` function directly, we should export a factory function, which will take an optional `streamAdapter` argument and produce an adapted `Collection` function (the static methods should get adapted there, too).

**Comment by geovanisouza92** [comment]
Is this ready for publishing on npm? I think that people could make use of the "diversity". :)

**Comment by Widdershin** [comment]
Yep, I'll publish this when I find some time :)

**Comment by Widdershin** [comment]
I have just published v0.4.0 with @geovanisouza92's diversity changes 😄

Thanks again for such a great first contribution.
